version: "3.8"
services:
  db:
    image: postgres:15
    container_name: local_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_local_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
