import "~/styles/globals.css";

import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton  } from "@clerk/nextjs";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";

// Helper to show the environment in the title
let titleEnv = ''
if(process.env.APPLICATION_ENV == "production"){
  titleEnv += '<<production>>'
}
else {
  titleEnv += '{dev}'
}

export const metadata: Metadata = {
  title: "Recspenses App | " + titleEnv,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex items-center justify-between flex-wrap bg-slate-800">
      <div className="flex items-center flex-shrink-0 text-white mr-6 ml-6">
        <span className="font-semibold text-xl tracking-tight">Recspenses</span>
        <span className="font-semibold text-xs tracking-tight ml-2 text-yellow-400">{titleEnv}</span>
      </div>
      <div className="w-full block flex-grow lg:flex lg:items-center lg:w-auto p-4">
        <div className="text-l lg:flex-grow p-6">
          <Link className="mr-3 text-gray-300 hover:text-white" href="/">Home</Link>
          <Link className="mr-3 text-gray-300 hover:text-white" href="/dashboard">Dashboard</Link>
        </div>
        <div>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </div>
      </div>
      </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <TopNav />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
